version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ADZUNA_ID=${ADZUNA_ID}
      - ADZUNA_KEY=${ADZUNA_KEY}
      - FOUNDRY_ENDPOINT=${FOUNDRY_ENDPOINT}
      - FOUNDRY_KEY=${FOUNDRY_KEY}
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: jobsight
    ports:
      - "5432:5432"